global:
  scrape_interval: 900s # Default is every 1 minute.
  evaluation_interval: 900s # Default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  # Make Prometheus scrape itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "dowmetheus"
    static_configs:
      - targets: ["localhost:9927"]