apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  typeName: Prometheus
  typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
  access: direct
  url: http://localhost:9090
  user: ''
  database: ''
  basicAuth: false
  isDefault: true
  jsonData:
    httpMethod: POST
    manageAlerts: true
    timeInterval: 900s
    tlsSkipVerify: true
  readOnly: false
